"""Ajout des modèles Competency et Softskill et mise à jour de l'endpoint details

Revision ID: 3b08a273757b
Revises: 9e2f4a83f85d
Create Date: 2025-02-21 19:03:12.263456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b08a273757b'
down_revision = '9e2f4a83f85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('softskills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habilete', sa.String(length=255), nullable=False),
    sa.Column('niveau', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('softskills')
    op.drop_table('competencies')
    # ### end Alembic commands ###
