"""Ajout du champ shape_id dans Activities (et Data si nécessaire)

Revision ID: 90f8295e9ee7
Revises: 3b08a273757b
Create Date: 2025-02-22 17:02:21.603514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f8295e9ee7'
down_revision = '3b08a273757b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('softskills', schema=None) as batch_op:
        batch_op.alter_column('niveau',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('softskills', schema=None) as batch_op:
        batch_op.alter_column('niveau',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
