"""Ajout du champ onboarding_plan dans Role

Revision ID: f921f6857574
Revises: 37f4fdd5526b
Create Date: 2025-03-01 17:20:20.363816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f921f6857574'
down_revision = '37f4fdd5526b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_plan', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('onboarding_plan')

    # ### end Alembic commands ###
