"""Ajout du champ shape_id dans Activities (et Data si nécessaire)

Revision ID: 9145e7c03be0
Revises: 90f8295e9ee7
Create Date: 2025-02-22 17:12:01.565771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9145e7c03be0'
down_revision = '90f8295e9ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shape_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_activities_shape_id'), ['shape_id'], unique=True)

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.alter_column('source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('target_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shape_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_data_shape_id'), ['shape_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_shape_id'))
        batch_op.drop_column('shape_id')

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('source_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_shape_id'))
        batch_op.drop_column('shape_id')

    # ### end Alembic commands ###
